---
:info: {}
:num_page_style: num_parags
:headers:
- :pages: "(2..8)"
  :disposition:
    :even: "%{title1}- |  |"
    :odd: "| | -%{TITLE1}"
  :font: Arial
  :size: 8
  :style: :normal
# - :pages: "(9..14)"
#   :disposition:
#     :even: "%{title2}- | |"
#     :odd: "| | -%{title2}"
#   :font: Arial
#   :size: 8
#   :style: :normal
:footers:
- :pages: "(4..14)"
  :disposition:
    :odd: "| -%{numero}- |"
    :even: "| -%{numero}- |"
  :font: Arial
  :size: 8
  :style: :normal
:book_title: Titre du livre
:book_subtitle: "Le sous-titre du livre où\nles retours chariot seront \nconservés
  et affiché\n"
:collection: true
:book_id: debut
:auteurs:
- Prénom NOM
:main_folder: "/Users/philippeperret/Programmes/Prawn4book/resources/renders/debut"
:text_path: true
:infos:
  :display: false
  :isbn:
  :depot_bnf: 3e trimestre 2022
  :cover: MM & PP
  :mep:
  - Prénom NOM
  :conception:
  - Prénom NOM
  :corrections:
  - Prénom NOM
  :print: Imprimé à la demande
:publisher:
  :name: Nom de l'éditeur
  :adresse: "xxx rue de Loraine \nxxxxxx Ville\n"
  :site: https://icare-editions.fr
  :logo:
  :siret: 508 680 360 00023
  :mail: publisher@edition.fr
  :contact: contact@edition.fr
:fonts:
  Garamond:
    :normal: "/Users/philippeperret/Library/Fonts/ITC - ITC Garamond Std Light Condensed.ttf"
    :italic: "/Users/philippeperret/Library/Fonts/ITC - ITC Garamond Std Light Condensed
      Italic.ttf"
  Bangla:
    :normal: "/System/Library/Fonts/Supplemental/Bangla MN.ttc"
    :bold: "/System/Library/Fonts/Supplemental/Bangla MN.ttc"
  Avenir:
    :normal: "/System/Library/Fonts/Avenir Next Condensed.ttc"
  Arial:
    :normal: "/Users/philippeperret/Library/Fonts/Arial Narrow.ttf"
  Nunito:
    :normal: "/Users/philippeperret/Programmes/Prawn4book/resources/fonts/Nunito_Sans/NunitoSans-Regular.ttf"
    :bold: "/Users/philippeperret/Programmes/Prawn4book/resources/fonts/Nunito_Sans/NunitoSans-Bold.ttf"
  Symbol:
    :normal: "/System/Library/Fonts/Symbol.ttf"
:dimensions:
- 127mm
- 203.2mm
:layout: :portrait
:marges:
  :top: 20mm
  :ext: 10mm
  :bot: 10mm
  :int: 25mm
:default_font: Garamond
:default_font_size: 11
:default_font_style: :normal
:line_height: 14
:interligne:
:leading: 1
:opt_num_parag: true
:num_parag:
  :top_adjustment: 0
:skip_page_creation: true
:page_de_garde: false
:faux_titre: false
:page_de_titre: false
:page_info: true
:table_of_content:
  # :title: false # pas de titre
  :first_line:  10
:titles:
  :level1:
    :next_page: true
    :belle_page: true
    :font: Nunito
    :size: 30
    :margin_top: 4
    :margin_bottom: 4
    :leading: -2
  :level2:
    :font: Nunito
    :size: 26
    :margin_top: 2
    :margin_bottom: 1
    :leading: -2
  :level3:
    :font: Nunito
    :size: 20
    :margin_top: 2
    :margin_bottom: 1
    :leading: -2
  :level4:
    :font: Nunito
    :size: 16
    :margin_top: 1
    :margin_bottom: 0
    :leading: -2
:biblio:
- :tag: livre
  :title: Liste des ouvrages cités
  :title_level: 2
  :data: biblio/livres.yaml
  :new_page: false
- :tag: film
  :title: Films cités
  :title_level: 2
  :data: biblio/films
  :new_page: false
:references:
  :cross_references:
    :autrelivre: faux/path
    :crbook: "../cross_book"
