---
#<book_data>
book_data:
  title: "Manuel de Prawn-for-book"
  author: "Philippe PERRET"
#</book_data>

#<book_making>
book_making:
  conception:
    patro: "Philippe PERRET"
    mail:  "philippe.perret@icare-editions.fr"
  design:
    patro: "Prawn-For-Book"
    mail: null
  cover:
    patro: "MM & PP"
    mail: null
  correction:
    patro: ["Marion MICHEL"]
    mail:  [null]
#<book_format>
book_format:
  page:
    show_grid: false
    show_margins: false
  book:
    width:  '210mm'
    height: '297mm'
    orientation: 'portrait'
    format: :pdf
  text:
    default_font_and_style: 'Numito/light'
    default_font_size:  11
    line_height: 18
    guillemets:               ['« ',' »']
  #<titles>
  titles:
    level1:
      lines_before: 10
      size:         30
      align: :right
      alone: true
    level2:
      lines_before: 10
      size:         22
      align: :right
      alone: true
    level3:
      color: '0000AA'
    level4:
      lines_before: 2
      lines_after:  1
      color: '00AA00'
    level5:
      lines_before: 0
  #</titles>
#</book_format>

#<headers_footers>
headers_footers:
  dispositions:
    default:
      name: "Dispositions pages fonctionnalités"
      pages: "16-"
      header: "| TIT3- || -TIT4 |"
      footer: "| -NUM  || NUM-  |"
      header_font: "Numito/light/10/999999"
      footer_font: "Numito/bold/13/333333"
#</headers_footers>

#<table_of_content>
table_of_content:
  # title: "Table des matières"
  no_title: true
  level_max: 3
  lines_top: 4
  lines_bottom:  4
  font: "Helvetica/normal/12/000000"
  line_height:  18
  vadjust_line: -3
  vadjust_number: 0
  dash_line: {length: 1, phase: 0, space: 3, color: "888888"}
  # line_height: 20
  level1:
    caps: "all-caps"
  level2:
    caps: none
  level3:
    caps: none
#</table_of_content>

#<credits_page>
credits_page:
  disposition: "distribute"
#</credits_page>
book_making:
  conception:
    patro: "Philippe PERRET"
    mail: "philippe.perret@icare-editions.fr"
#<book_making>
#</book_making>
