---
#<book_data>
book_data:
  title: "Manuel de Prawn-for-book"
  author: "Philippe PERRET"
#</book_data>

#<book_format>
book_format:
  page:
    show_grid: false
    show_margins: false
  book:
    width:  '210mm'
    height: '297mm'
    orientation: 'portrait'
    format: :pdf
  text:
    default_font_and_style: 'Numito/light'
    default_font_size:  11
    line_height: 18
    guillemets:               ['« ',' »']
  #<titles>
  titles:
    level1:
      lines_before: 10
      align: :right
      alone: true
    level3:
      color: '0000AA'
    level4:
      lines_before: 2
      lines_after:  1
      color: '00AA00'
    level5:
      lines_before: 0
  #</titles>
#</book_format>

