---
#<book_data>
book_data:
  title: "Manuel de Prawn-for-book"
  subtitle: "le manuel autoproduit de l’application\\nde mise en forme professionnelle"
  author: "Philippe PERRET"
  isbn: null
  url:  null
#</book_data>

#<book_making>
book_making:
  conception:
    patro: "Philippe PERRET"
    mail:  "philippe.perret@icare-editions.fr"
  page_design:
    patro: "Prawn-For-Book"
    mail: null
  cover:
    patro: "MM & PP"
    mail: null
  correction:
    patro: ["Marion MICHEL"]
    mail:  [null]
#<book_format>
book_format:
  page:
    show_grid: false
    show_margins: false
  book:
    width:  '210mm'
    height: '297mm'
    orientation: 'portrait'
    format: :pdf
  text:
    default_font_and_style: 'Numito/light'
    default_font_size:  11
    line_height: 14
    guillemets:               ['« ',' »']
  #<titles>
  titles:
    level1:
      lines_before: 10
      size:         30
      align: :right
      alone: true
    level2:
      lines_before: 10
      size:         22
      align: :right
      alone: false
    level3:
      color: '0000AA'
    level4:
      lines_before: 2
      lines_after:  1
      color: '00AA00'
    level5:
      lines_before: 2
      lines_after: 1
      alone: false
      next_page: false
      belle_page: false
      caps: "all-caps"

  #</titles>
#</book_format>

#<inserted_pages>
inserted_pages:
  credits_page:
    disposition: "distribute"
  page_de_titre:
    title:
      font: "Numito/normal/30/FF0000"
      line: 15
    subtitle:
      font: "Numito/italic/16/007700"
      line: 16
    author:
      font: "Numito/normal/18/000077"
      line: 22
    publisher:
      font: "Numito/normal/12/FF8000"
      line: 2
      logo:
        height: 40
        line: 3

#</inserted_pages>

#<headers_footers>
headers_footers:
  dispositions:
    default:
      name: "Dispositions pages fonctionnalités"
      pages: "16-"
      header: "| TIT3- || -TIT4 |"
      footer: "| -NUM  || NUM-  |"
      header_font: "Numito/light/10/999999"
      footer_font: "Numito/bold/13/333333"
#</headers_footers>

#<table_of_content>
table_of_content:
  # title: "Table des matières"
  no_title: true
  level_max: 3
  lines_top: 4
  lines_bottom:  4
  font: "Helvetica/normal/12/000000"
  line_height:  18
  vadjust_line: -3
  vadjust_number: 0
  dash_line: {length: 1, phase: 0, space: 3, color: "888888"}
  # line_height: 20
  level1:
    caps: "all-caps"
  level2:
    caps: none
  level3:
    caps: none
#</table_of_content>


#<book_making>
book_making:
  conception:
    patro: "Philippe PERRET"
    mail: "philippe.perret@icare-editions.fr"
  page_design:
    patro: "Prawn-For-Book"
  cover:
    patro: "=MM & PP"
  correction:
    patro: "Marion MICHEL"
  printing:
    name: "Prawn-For-Book"
#</book_making>

#<publisher>
publisher:
  name: "Icare Éditions"
  logo_path: "logo/couleur.jpg"
#</publisher>

#<bibliographies>
bibliographies:
  article:
    title: "Articles de presse"
    title_level: 2
    path: "biblios/articles"
    picto: :fiche
  film:
    title: "Films cités"
    title_level: 2
    path: "biblios/films"
    picto: clap
    format: "%{title|all_caps} (%{year} — %{year|age}, réalisation : %{director|person}, acteurs : %{actors|person}, durée : %{duration|minute_to_horloge}). Occurrences : %{pages}"
  costum:
    title: "Liste des costumes"
    title_level: 3
    path: "biblios/costums"
    main_key: nom
    format: "%{nom|transforme_nom}"

#</bibliographies>
