---
#<book_data>
book_data:
  title: "Manuel de Prawn-for-book"
  author: "Philippe PERRET"
#</book_data>

#<book_format>
book_format:
  page:
    show_grid: false
    show_margins: false
  book:
    width:  '210mm'
    height: '297mm'
    orientation: 'portrait'
    format: :pdf
  text:
    default_font_and_style: 'Numito/light'
    default_font_size:  11
    line_height: 18
    guillemets:               ['« ',' »']
  #<titles>
  titles:
    level1:
      lines_before: 10
      size:         30
      align: :right
      alone: true
    level2:
      lines_before: 10
      size:         22
      align: :right
      alone: true
    level3:
      color: '0000AA'
    level4:
      lines_before: 2
      lines_after:  1
      color: '00AA00'
    level5:
      lines_before: 0
  #</titles>
#</book_format>

#<headers_footers>
headers_footers:
  dispositions:
    default:
      name: "Dispositions pages fonctionnalités"
      pages: "16-"
      header: "| TIT3- || -TIT4 |"
      footer: "| -NUM  || NUM-  |"
      header_font: "Numito/light/10/999999"
      footer_font: "Numito/bold/13/333333"
#</headers_footers>

#<table_of_content>
table_of_content:
  font: "Helvetica/regular/12/000000"
  number_font: "Helvetica/italic/12/FF0000"
  dash_line: {length: 5, phase: 6, space: 0, color: "DDDDDD"}
  # line_height: 20
  level1:
    caps: "all-caps"
  level2:
    caps: none
  level3:
    caps: none
#</table_of_content>
