---
:book_title:    Le titre du livre à 07 10 2022 - 18:44
:auteurs:      Philippe Perret
:book_id:      mon_livre
:main_folder: "/Users/philippeperret/Programmes/Prawn4book/tests/essais/books/mon_livre"
:text_path:   true
:dimensions : ['127mm', '203.2mm']
:marges:
  :top: '20mm'
  :bot: '20mm'
  :ext: '20mm'
  :int: '20mm'
:opt_para_num: false
:default_font: Garamond
:default_font_size: 11
:default_baseline:  12
:titles:
  :level1:
    :font: 'Nunito'
    :next_page: true
    :size: 24
    :margin_top: 0
    :margin_bottom: 4
    :leading: -10
  :level2:
    :font: 'Nunito'
    :next_page: false
    :size: 16.5
    :margin_top: 4
    :margin_bottom: 2
    :leading: -6
:fonts:
  Garamond:
    :normal: "/Users/philippeperret/Library/Fonts/ITC - ITC Garamond Std Light Condensed.ttf"
    :italic: "/Users/philippeperret/Library/Fonts/ITC - ITC Garamond Std Light Condensed Italic.ttf"
  Bangla:
    :normal: "/System/Library/Fonts/Supplemental/Bangla MN.ttc"
    :bold:   "/System/Library/Fonts/Supplemental/Bangla MN.ttc"
  Avenir:
    :normal: "/System/Library/Fonts/Avenir Next Condensed.ttc"
  Arial:
    :normal: "/Users/philippeperret/Library/Fonts/Arial Narrow.ttf"
  Nunito:
    :normal: "/Users/philippeperret/Programmes/Prawn4book/resources/fonts/Nunito_Sans/NunitoSans-Regular.ttf"
    :bold:   "/Users/philippeperret/Programmes/Prawn4book/resources/fonts/Nunito_Sans/NunitoSans-Bold.ttf"
