---
:book_title:   Livre d'aspect et de test
:auteurs:      ['Philippe PERRET']
:book_id:      mon_livre
:main_folder: "/Users/philippeperret/Programmes/Prawn4book/tests/essais/books/mon_livre"
:text_path:   true
:dimensions: ['127mm', '203.2mm']
:layout: :portrait
:page_de_garde:       true
:page_de_titre:       true
:faux_titre:          true
:table_of_contents:  true
:infos:
  :display:     true
  :isbn:        2546-6987-45879-8
  :depot_bnf:   4e trimestre 2022
  :cover:       "MM & PP" # auteurs de la couverture
  :mep:         ['Cédric DE MONDÉNARD']
  :conception:  ['Philippe PERRET']
  :corrections: ['Marion MICHEL']
  :print:       'Imprimé à la demande'
:publisher:
  :name:  MAISON D’ÉDITIONS
  :adresse: |
    295 place des Lilas
    13400 Aubagne
  :site:      'https://icare-editions.fr'
  :logo:      "/Users/philippeperret/Library/Mobile Documents/com~apple~CloudDocs/ICARE_EDITIONS/Divers/xImages/Logo/Officiel/logo-gris-moyen.jpg"
  :siret:     '508 680 360 00023'
  :mail:      editions@icare-editions.fr
  :contact:   contact@icare-editions.fr

:marges:
  :top: '20mm'
  :bot: '20mm'
  :ext: '20mm'
  :int: '20mm'
:opt_para_num: false
:default_font: Garamond
:default_font_size: 11
:line_height:  12.5
:titles:
  :level1:
    :font: 'Nunito'
    :next_page: true
    :size: 24
    :margin_top: 0
    :margin_bottom: 4
    :leading: -10
  :level2:
    :font: 'Nunito'
    :next_page: false
    :size: 16.5
    :margin_top: 4
    :margin_bottom: 2
    :leading: -6
:fonts:
  Garamond:
    :normal: "/Users/philippeperret/Library/Fonts/ITC - ITC Garamond Std Light Condensed.ttf"
    :italic: "/Users/philippeperret/Library/Fonts/ITC - ITC Garamond Std Light Condensed Italic.ttf"
  Bangla:
    :normal: "/System/Library/Fonts/Supplemental/Bangla MN.ttc"
    :bold:   "/System/Library/Fonts/Supplemental/Bangla MN.ttc"
  Avenir:
    :normal: "/System/Library/Fonts/Avenir Next Condensed.ttc"
  Arial:
    :normal: "/Users/philippeperret/Library/Fonts/Arial Narrow.ttf"
  Nunito:
    :normal: "/Users/philippeperret/Programmes/Prawn4book/resources/fonts/Nunito_Sans/NunitoSans-Regular.ttf"
    :bold:   "/Users/philippeperret/Programmes/Prawn4book/resources/fonts/Nunito_Sans/NunitoSans-Bold.ttf"
:page_info: 

