---

# --- Infos sur le livre ---
:book_title: %{thing_title}
:book_subtitle: |
  %{subtitle}
:collection: true     # true => dans une collection
:book_id: %{thing_title}
:auteurs: %{auteurs}
:main_folder: %{main_folder}
:text_path: true # true = texte.md ou texte.txt dans ce dossier
:infos:
  :display:     %{pageinfos}
  :isbn:        %{isbn}
  :depot_bnf:   %{depot}
  :cover:       %{cover_conception}
  :mep:         %{mep}
  :conception:  %{book_conception}
  :corrections: %{correction}
  :print:       %{mark_print}

# --- INFOS LIVRE ou COLLECTION ---

