---

# --- Infos sur le livre ---
#<book_data>
:book_title: %{book_title}
:book_subtitle: |
  %{book_subtitle}
:collection: true     # true => dans une collection
:book_id: %{book_title}
:auteurs: %{book_author}
:isbn:    %{book_isbn}
:publisher:
  :name:  "%{publisher_name}"
  :adresse: |
    %{publisher_address}
  :site:      '%{publisher_site}'
  :logo:      '%{publisher_logo}'
  :siret:     '508 680 360 00023'
  :mail:      '%{publisher_mail}'
  :contact:   '%{publisher_contact}'
#</book_data>
:main_folder: %{main_folder}
:text_path: true # true = texte.md ou texte.txt dans ce dossier
:infos:
  :display:     %{pageinfos}
  :depot_bnf:   %{depot}
  :cover:       %{cover_conception}
  :mep:         %{mep}
  :conception:  %{book_conception}
  :corrections: %{correction}
  :print:       %{mark_print}

# --- INFOS LIVRE ou COLLECTION ---

