---

# --- Infos sur le livre ---
:book_title: Titre du livre
:book_subtitle: |
  Le sous-titre du livre où
  les retours chariot seront 
  conservés et affiché
:collection: true     # true => dans une collection
:book_id: mon_livre
:auteurs: ['Prénom NOM']
:main_folder: "/absolute/path/to/this/folder"
:text_path: true # true = texte.md ou texte.txt dans ce dossier
:infos:
  :display:     true
  :isbn:        null
  :depot_bnf:   3e trimestre 2022
  :cover:       "MM & PP" # auteurs de la couverture
  :mep:         ['Prénom NOM']
  :conception:  ['Prénom NOM']
  :corrections: ['Prénom NOM']
  :print:       'Imprimé à la demande'

# --- INFOS LIVRE ou COLLECTION ---

