---

# --- Infos sur le livre ---
:book_title: Titre du livre
:book_subtitle: |
  Le sous-titre du livre où
  les retours chariot seront 
  conservés et affiché
:collection: true     # true => dans une collection
:book_id: mon_livre
:auteurs: ['Prénom NOM']
:main_folder: "/absolute/path/to/this/folder"
:text_path: true # true = texte.md ou texte.txt dans ce dossier

# --- INFOS LIVRE ou COLLECTION ---

