---

# --- Infos sur le livre ---
:book_title: Titre du livre
:book_subtitle: |
  Le sous-titre du livre où
  les retours chariot seront 
  conservés et affiché
:collection: true     # true => dans une collection
:book_id: mon_livre
:auteurs: ['Prénom NOM']
:main_folder: "/absolute/path/to/this/folder"
:text_path: true # true = texte.md ou texte.txt dans ce dossier
:editor:         :collection # données de l'éditeur

# --- Fontes à empaqueter ---
# :fonts:           :collection # Si collection
:fonts:
  FontName:
    :normal: "/path/to/font.ttf"
    :italic: "/path/to/font-italic.ttf"

# --- Options pour les pages ---
:dimensions:      :collection # dimensions du livre
:marges:          :collection # marges
:interligne:      :collection # interlilgne
# :opt_num_parag:   :collection # si collection
:opt_num_parag:   true # true => numéroter les paragraphes
# :num_page_style:  :collection # si collection
:num_page_style:  num_page # style de numérotation des pages

# --- Pages à insérer ---
# :faux_titre:      :collection # si collection
:faux_titre:      false # true => insérer la page de faux-titre
# :page_de_garde:   :collection # si collection
:page_de_garde:   true  # true => insérer la page de garde
# :page_info:       :collection # si collection
:page_info:       # => page de fin avec les infos
  :display: true  # true
  :isbn:    null
  :depot_bnf: 3e trimestre 2022
  :cover:     MM & PP # auteurs de la couverture
  :mail:      editions@icare-editions.fr

# --- Table Des Matières ---
# :tdm:             :collection # si collection
:tdm:
  # Distance du numéro de page avec la marge droite
  :dist_num_from_rmargin: 0

# --- Entête du livre ---
# :header: :collection # si collection
:header: # tous les rangs
  - :from_page: 10
    :to_page: 200
    :disposition: "| -%titre1- |"
    :font: ArialNarrow
    :size: 8
    :style: :bold

# --- Pied de page ---
# :footer: :collection # si collection
:footer: # tous les rangs
  - :from_page: 10
    :to_page: 20
    :disposition: "-%titre1 | |"
    :font: Arial
    :size: 8
    :style: :bold

# --- Titres ---
:titles:
  :level1:
    :font: Nunito
    :size: 30
  :level2:
    :font: Nunito
    :size: 26
  :level3:
    :font: Nunito
    :size: 20
  :level4:
    :font: Nunito
    :size: 16
