---
bibliographies:
  book:
    title: Livres
    path: assets/biblios/books
    picto: book
    format: "%{title} (%{author|monauteur})"
    number:
      font: "Helvetica/italic/9/555555"
      main: 
        font: "Helvetica/bold/10/000000"
      minor:
        font: "Helvetica/light/8/999999"

inserted_pages:
  #
  # Aspect pour la page d’index
  #
  page_index:
   aspect:
      canon: "//14/007700"
      number:
        font: "Helvetica/italic/9/555555"
        main: 
          font: "Helvetica/bold/9.5/000000"
        minor:
          font: "Helvetica/italic/8.5/999999"
  #
  #
  #
  page_de_garde: false
  page_de_titre: false
  faux_titre: false