table_of_content:
  title: "Sommaire"
book_format:
  titles:
    level1:
      lines_after: 0
      lines_before: 0
      next_page:  false # pour ne pas ajouter de page avant
      belle_page: false # idem
      alone: false