---
book_format:
  book:
    width: 210mm
    height: 297mm
  titles:
    level1:
      new_page: false
      belle_page: false
      alone: false
      align: :center
table_of_content:
  title:      "Mon Sommaire"
  no_title:   false
  numeroter:  false
  level_max:  4
  line_height: 24
  level1:
    font: "Helvetica/light/15/55A200"
    numero_size: 12
  level2:
    dash: {color: "0000FF"}
  level3:
    indent: 6cm
    numero_size: 10
    caps: "all-caps"
    dash: {length: 10, space: 2} 
  level4:
    font: "Reenie/normal/15/FF0000"
    numero_size: 10
    dash: {length: 1, space: 3} 
